name: weather_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_it: ^8.0.3
  dio: ^5.8.0+1
  get_storage: ^2.1.1
  #intl: #^0.20.2
  internet_connection_checker: ^3.0.1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.3
  path_provider: ^2.0.15

 # pusher_channels_flutter: ^2.5.0

  flutter_widget_from_html_core: ^0.15.2

  # for update
  in_app_update: ^4.2.3

  #url launch
  url_launcher: ^6.1.7

  # for messages
  fluttertoast: ^8.2.11

  # for design
  # modal_bottom_sheet: ^2.0.0
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.2.1
  pinput: ^2.2.12
  zoom_widget: ^2.0.0
  easy_stepper: ^0.8.5+1

  carousel_slider: ^5.1.1
  intl_phone_field: ^3.2.0
  google_fonts: ^6.2.1

  # for images
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  device_info_plus: ^10.1.0
  flutter_screenutil: ^5.9.0

  chucker_flutter: ^1.8.5
  
  cached_network_image: ^3.4.1
  file_picker: ^8.3.2
  font_awesome_flutter: ^10.8.0
  mime: ^2.0.0
  #device_preview: ^1.3.1
  fl_chart: ^0.70.2
  flutter_xlider: ^3.5.0
  table_calendar: ^3.1.3
  smooth_page_indicator: ^1.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  supabase_flutter: ^2.10.3
  flutter_image_compress: ^2.4.0
  cloudinary_public: ^0.23.1
  google_maps_flutter: ^2.14.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  firebase_auth_mocks: ^0.15.1
  fake_cloud_firestore: ^4.0.1
  google_sign_in_mocks: ^0.4.1
  mockito: ^5.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/lotties/
    - assets/svg/

flutter_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"


  # To add assets to your application, add an assets section, like this:


  # fonts:
  #   - family: Almarai
  #     fonts:
  #       - asset: assets/fonts/ArbFONTS-Almarai-ExtraBold.ttf
  #         weight: 700
  #       - asset: assets/fonts/ArbFONTS-Almarai-Bold.ttf
  #         weight: 600
  #       - asset: assets/fonts/ArbFONTS-Almarai-Regular.ttf
  #         weight: 500
  #       - asset: assets/fonts/ArbFONTS-Almarai-Light.ttf
  #         weight: 400
  #   - family: Arial
  #     fonts:
  #       - asset: assets/fonts/arial/arial-bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/arial/arial-semibold.TTF
  #         weight: 600
  #       - asset: assets/fonts/arial/arial-regular.ttf
  #         weight: 500
  #   - family: Digital
  #     fonts:
  #       - asset: assets/fonts/digital/digital-7 (mono).ttf
  #         weight: 700
  #       - asset: assets/fonts/digital/digital-7 (mono).ttf
  #         weight: 600
  #       - asset: assets/fonts/digital/digital-7 (italic).ttf
  #         weight: 500

  #
  #
  #   - family: SegoeUi
  #     fonts:
  #       - asset: assets/fonts/SEGOEUI.TTF


